name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : checkout
      uses: actions/checkout@v4

    - name: python install
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'

    - name: Install dependencies
      run: make init

    - name: Test
      run: make test


    
